### PR TITLE
Modify promotion pipelines and fix prod mq infra instance sync policy

### PR DESCRIPTION
**Pull request by phemankita**

### CODE REVIEW

**Review by hollisc — CHANGES_REQUESTED** [review]
@phemankita, it was intentional to not add the `Replace=true` syncOption for `mq-infra` in production.  We can set this for the other env but do not want to do this for prod.

**Comment by phemankita** [comment]
> @phemankita, it was intentional to not add the `Replace=true` syncOption for `mq-infra` in production. We can set this for the other env but do not want to do this for prod.

@hollisc  Initally `auto-sync` is off too. I enabled it, do we want to keep and just rm the `syncOption` for mq-infra ? 

For `spring app` we have the `syncOption` set. Do we want to rm that as well ?

**Comment by hollisc** [comment]
> > @phemankita, it was intentional to not add the `Replace=true` syncOption for `mq-infra` in production. We can set this for the other env but do not want to do this for prod.
> 
> @hollisc Initally `auto-sync` is off too. I enabled it, do we want to keep it and just rm the `syncOption` for mq-infra or remove auto-sync as well ?

@phemankita, can we disable auto-sync as well for prod.

**Review by hollisc — APPROVED** [review]
Looks good

**Pull request merged**
